Fix the frontend displaying issue
kernelci/kernelci-frontend pull request #42
Opened 2019-03-05 15:41 UTC by touilkhouloud

Actually the line in the code where to call the test case data is
in the wrong place, so this patch change the position of thid line
to the right one.

Signed-off-by: Khouloud Touil <ktouil@baylibre.com>

2019-03-06 08:01 UTC, khilman commented
Changelog needs work.

Why is it wrong?  What problem does it cause, and how does your solution fix the problem?

2019-03-06 13:55 UTC, khilman requested changes
This changelog still doesn't describe what the actual problem is, and how the patch fixes it.   It mentions "a problem" but doesn't say what it is.

2019-03-08 18:21 UTC, khilman approved these changes
@MiloCasagrande does this look OK to you?

2019-05-13 21:50 UTC, khilman commented
@gctucker @MiloCasagrande any comments on this fix?

2019-05-13 23:21 UTC, MiloCasagrande commented
I'm not sure why nor what this change should fix.
`getTestCaseData` should be called at the end of `getBootLog`, so I don't see what the actual problem is.

Doesn't it get called? Are there other problems in the code?

2019-05-16 12:18 UTC, touilkhouloud commented
@MiloCasagrande getTestCaseData should not be blocked by getBootLog as they are two different functionalities.
We had a problem in kernelci.baylibre when displaying supgroup data, there is something wrong with the getBootLog function so it blocked the data display, I've fixed that problem with this patch 
in here you can see that we have the data well displayed but there is a problem with getBootLog (supgroup data cases) http://kernelci.dev.baylibre.com:8080/test/group/5cd27d95f1bfe506d6a13073/

2019-05-16 15:13 UTC, MiloCasagrande requested changes
Now I understand the issue, but you are only going around it here.

I'm fine with moving the call to `getTestCaseData` (remove the `setTimeout` at this point though), but the real issue should be investigated and solved.

2019-05-28 16:52 UTC, khilman commented
@MiloCasagrande patch updated as you requested.  We'll fix the underlying issue in a separate change.

2019-05-28 17:13 UTC, merged