T19387 - only show failed builds when landing on page
kernelci/kernelci-frontend pull request #75
Opened 2020-02-27 17:01 UTC by alexandrasp

remove all session storage in order to avoid
bugs and to only show failed builds when there is any
fail on build list.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

2020-02-27 20:44 UTC, gctucker reviewed
> remove all session storage in order to avoid
> bugs and to only show failed builds when there is any
> fail on build list.

The commit title should also show that this is about removing session storage, not just showing failed builds by default.

2020-02-27 22:10 UTC, gctucker requested changes
Well it's one thing to disable session storage, the problem is that the issue is still visible:
https://staging.kernelci.org/build/kernelci/branch/staging.kernelci.org/kernel/staging-20200226.0/

2020-02-27 22:12 UTC, gctucker commented
If you open the view above, you can see that the "Failed" button is active but both successful and failed builds are still visible in the list.  Only failed builds should be visible instead.

2020-02-27 22:17 UTC, alexandrasp commented
> If you open the view above, you can see that the "Failed" button is active but both successful and failed builds are still visible in the list. Only failed builds should be visible instead.

yes, I see. I will check this again, now I have the same problem locally.

2020-03-18 14:46 UTC, gctucker commented
This PR caused the staging update to fail in this ansible step:
```
TASK [configure-nginx : Build static assets]
```

2020-03-18 16:39 UTC, alexandrasp commented
> This PR caused the staging update to fail in this ansible step:
> 
> ```
> TASK [configure-nginx : Build static assets]
> ```

Ok, After finish main test view I will back to this problem.

2020-04-22 03:27 UTC, alexandrasp commented
@gctucker could you remove staging-skip ? I removed promise and now the code just wait for 1s for data to arrive and table to be built.

2020-04-22 08:34 UTC, gctucker commented on app/dashboard/static/js/app/view-builds-job-branch-kernel.2020.2.1.js
> +            });
Unnecessary whitespace noise

2020-04-22 08:45 UTC, gctucker commented
OK it's on staging now, the ansible issue is gone.

2020-04-22 08:52 UTC, gctucker requested changes
Well that appears to "work" but it's not an acceptable solution to just wait for one second every time this page is loaded and hope the results have been received in the meantime.

2020-04-22 11:02 UTC, alexandrasp commented
> Well that appears to "work" but it's not an acceptable solution to just wait for one second every time this page is loaded and hope the results have been received in the meantime.

I see and agree with you! It was good to see if it works on staging, now I will tune this solution.

2020-04-22 21:28 UTC, gctucker commented
I think I've fixed this problem with #91.

2020-04-22 22:10 UTC, closed without merging